### ISSUE TITLE
Compost bin would not produce bonemeal when configured

### ISSUE THREAD

**Issue by Stormwind99** [Stormwind99/Composter#5]
mcfan2 reports:

 Is there a way to make the compost bin actually create vanilla Bonemeal?
Compost looks nicer but it doesn't work with Immersive Engineering's Cloches. Putting minecraft:dye:15 or minecraft:dye@15 doesn't work.

https://minecraft.curseforge.com/projects/composter?comment=5

**Comment by mobeonsa** [comment]
Still have same problem. Even items without metadata.
minecraft:dye:15 | ore:dyeWhite | minecraft:iron
Composter seems to work, but after process complete nothing shows up in result.
P.S. Sorry for bad eng(

**Comment by Stormwind99** [comment]
You need to use "minecraft:dye@15" to get bonemeal.

In the next version, I added a "bonemeal" shortcut for you.

Here are screenshots of it working:
![2018-07-22_16 58 54](https://user-images.githubusercontent.com/9441438/43050654-86b5d10c-8dd2-11e8-9a4b-1043e5f256fc.png)
![2018-07-22_16 59 06](https://user-images.githubusercontent.com/9441438/43050655-8a06552a-8dd2-11e8-9bed-f6ba52795357.png)
