### ISSUE TITLE
Game crashes at load

### ISSUE THREAD

**Issue by Priderino** [Stormwind99/Composter#7]
Game crashes after I updated to version 1.3.0, it didn't happen with 1.2.0.
Forge: 14.23.4.2739
Composter: 1.3.0
Food Funk: 3.0.0
Crashlog: https://paste.dimdev.org/izihifunis.mccrash

**Comment by Stormwind99** [comment]
Very odd - the JVM doesn't think the com.wumple.util.TypeIdentifier.build method exists.

```
java.lang.NoSuchMethodError: com.wumple.util.TypeIdentifier.build(Ljava/lang/String;)Lcom/wumple/util/TypeIdentifier;
    at com.wumple.composter.ObjectHolder$RegistrationHandler.registerItems(ObjectHolder.java:55)
```

Try the newer 1.3.2 version and make sure Wumple Util Library is also installed (which is now needed starting this version).
