### ISSUE TITLE
Adding new compostable stuff

### ISSUE THREAD

**Issue by UncleSam139** [Stormwind99/Composter#8]
I have add this stuff to my config file, maybe you want add this to the mod. If you want let me know, because there are some other mods like Biomes O' Plenty and Tinker Construct with lot of stuff to add.

Tickrate can be changed. ;-)

1. Minecraft and Pam's Harvestcraft - Seeds:
I:seedAllist=125

2. AgriCraft - Seeds:
I:"agricraft:agri_seed"=125

3. ATLCraft Candles Mod - Seeds:
I:"atlcraft:atlcraft_bayberry_seeds"=125

4. Garden Stuff - Seeds:
I:"gardenstuff:candelilla_seeds"=125

5. Hatchery - Chicken Manure + Chicken Feed:
I:"hatchery:chickenmanure"=125
I:"hatchery:chicken_feed"=125

**Comment by Stormwind99** [comment]
Thanks!  Those all make sense, I've added those to the default configuration.

Sure, I'll take more.  You can either create an issue like you did here, or if you want to make it easier for me you can submit a pull request with the additions made to the https://github.com/Stormwind99/Composter/blob/master/src/main/java/com/wumple/composter/config/ConfigHandler.java#L78 file.

**Comment by Stormwind99** [comment]
@UncleSam139 - BTW, do you know where seedAllist comes from?  I can't find the source of it.

**Comment by Stormwind99** [comment]
I found "listAllseed" in Pam's Harvestcraft at https://github.com/MatrexsVigil/harvestcraft/blob/33df1750b1dc0253bfa85017cd45b31332641a48/src/main/java/com/pam/harvestcraft/item/GeneralOreRegistry.java

**Comment by UncleSam139** [comment]
I will do. Today I have found out that many original Minecraft stuff isn't compostable. I will start with Minecraft and go through each mod I use. Will take some days, but on weekend I think I'm done.

So we will rock this. :-D
